version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=${MONGODB_URI}  # MongoDB Atlas connection string
      - JWT_SECRET=${JWT_SECRET}    # JWT Secret for authentication
      - PORT=5000                   # Port for backend
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    command: npm start

  # If you're using MongoDB Atlas, you don't need a local mongo service here.
  # If you want to use a local mongo service, uncomment the section below.
  # mongo:
  #   image: mongo
  #   volumes:
  #     - mongo-data:/data/db

volumes:
  mongo-data:
